# Generated by Django 4.2.8 on 2023-12-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_entrepreneur_products_alter_factory_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='debt_to_supplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
